---
version: "3.8"

services:
  bot:
    build:
      context: .
    working_dir: /usr/src/gamebot
    stop_signal: SIGINT
    restart: unless-stopped
    ports:
      - "3306:3306"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gamebot
      MYSQL_USER: gamebot
      MYSQL_PASSWORD: gamebot
    volumes:
      - gamebot-mysql-data:/var/lib/mysql

volumes:
  gamebot-mysql-data:
